### ISSUE TITLE
[Feature Request] Blending Potions in Cauldron

### ISSUE THREAD

**Issue by Rad586** [Netherite-QF/YourIdeas#3]
I think it would be fun to mix potions in cauldron(with configurable effect amounts), making cauldron more useful. I've seen mods like this, but neither do they support fabric 1.18.2, nor without having visual glitches with Sodium.
Steps to mix:
1. Put down a cauldron.
2. Shift+ right click while holding potion.

**Comment by orange809** [comment]
Just try Lychee
