### ISSUE TITLE
[Feature Request] Blocking server command toasts

### ISSUE THREAD

**Issue by Rad586** [Netherite-QF/YourIdeas#7]
Screenshot: [](https://i.postimg.cc/j2v3zgZj/image.png)

I couldn't find a 1.18.2 fabric mod bout setting global gamerules, so I tried FTBquests instead to make this feature possible.
But everytime I create a new world, the server command toasts pop up, which breaks the immersion of modpack.
Besides, it's awkward to have player knowing that I'm playing them a sound when certain tasks completed.
Idk if this feature is not possible to accomplish since I'm not a mod dev...

_我没能找到可以实现“全局游戏规则”的1.18.2的fabric模组，所以我用FTB任务模组实现了那个功能。
但是问题随之而来，每次进入世界，都会有非常出戏的提示跳出来。
此外，让玩家知道是我在给他们播放任务完成音效的时候特别尴尬。
因为我对模组开发一窍不通，所以我也不知道这个到底能不能、好不好实现，就只是提一嘴~_

**Comment by orange809** [comment]
你好,如果你正在开发一个整合包,你可以用kubejs实现这个,我们不会实现这个
